Towards changes for documentation to be repository specific
SciCatProject/scicatproject.github.io pull request #50
Opened 2024-06-03 12:33 UTC by LAShemilt

# Introduction
This PR makes changes to the SciCat Website to make it a more user and developer friendly resource for documentation. 

In order to make this change there are a few larger structural changes to be made across the Scicat project which will be formed as part of companion pull requests into repositories. The proposed changes are these:

1) the ScicatProject/documentation repository becomes the User guide only, this will be eventually integrated into this website
2) All the repositories will have their own documentation. This can be easily amended when a developer makes a change to the website. 
3) The existing information in the Developers part of the documentation will go into backend docs, and frontend docs. 
4) All documentation will be linked to through the website.
# Proposed changes
* Resources formerly a mix of documentation and code becomes, Documentation. 
* All links in the Documentation section  will eventually point to a repository's documentation
* Descriptions have been changed to be more user friendly including Getting Started and User Guides, which could point to sections of documentation.

2024-06-03 12:50 UTC, nitrosx commented on _config.yml
@LAShemilt couple of questions:
- are we getting completely away from the current documentation pages under scicatproject.github.io/documentation? 
  I thought that we were maintaining the same style at the same URL but pulling the source files directly from the individual repositories?
- If we point to the files under the docs folder of each repos, we will loose the ability to move between sections through the side bar

2024-06-03 13:48 UTC, nitrosx commented
Here is the documentation for the current tool that we use to build the documentation pages:

2024-07-16 15:54 UTC, LAShemilt commented on _config.yml
on second thoughts we will repurpose the documentation pages under scicatproject.github.io/documentation as the user guides. This would, as you say, maintain the same style URLS for all the repositories. 

On point two I will amend the PR so we are just pointing to the top URLs, not files and then we can update the other repositiories at a later date.

2024-07-24 13:52 UTC, nitrosx requested changes

2024-07-24 13:52 UTC, nitrosx commented on README.md
> +This can be done by simply running the following from the projlect directory:
project mispelled

2024-07-24 13:52 UTC, nitrosx commented on _config.yml
I'm wondering if it would be better to compile the backend and frontend documentation and make it available also under _https://scicatproject.github.io/backend_ and _https://scicatproject.github.io/frontend_ instead of sending the user to the repository?

2024-07-24 13:56 UTC, nitrosx commented on _config.yml
This would be consistent with scicatlive documentation

2024-07-25 08:02 UTC, LAShemilt commented on _config.yml
yes I agree. I think this would be a nice trend for all the documentation to follow

2024-07-25 08:12 UTC, LAShemilt commented on _config.yml
do you want to make this change now before the URLs exist? Or shall we set up the documentation workflow on scicatb ackend and frontend?

2024-07-26 11:27 UTC, nitrosx approved these changes

2024-07-26 11:27 UTC, nitrosx commented on _config.yml
Let's leave it like this and open an issue to remind us about it.

2024-07-26 12:46 UTC, nitrosx approved these changes

2024-07-26 12:46 UTC, merged